### ISSUE TITLE
excluding text

### ISSUE THREAD

**Issue by 2013kaa** [feeltheajf/trufflehog3#41]
Hey
Tell me, do I understand correctly that in the new version there is only the ability to exclude folders ( -е / --exclude) and lines where the comment is (# nosecret)? Is the --skip_strings parameter not supported in the new version and there are no analogues?

If .trufflehog3.yml is used for this, could you please suggest the syntax for excluding the following text from all rules:
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789

**Comment by feeltheajf** [comment]
Hey @2013kaa 

I believe it should be something like this

```yaml
exclude:
  - message: Alphabet string, not a secret 
    pattern: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
```

I suggest you to check out the [.trufflehog3.yml](https://github.com/feeltheajf/trufflehog3/blob/master/.trufflehog3.yml) for more examples
